spring:
  config:
    activate:
      on-profile: test

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.DataRedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.DataRedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.DataRedisRepositoriesAutoConfiguration

  #  datasource:
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5433/my_api
  #    username: postgres
  #    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

app:
  payment-link-base-url: "http://localhost:8080"

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"

jwt:
  access_secret: testAccessSecretKeyForTestingPurposesMinimum256Bits