server:
  port: 8080

spring:
  application:
    name: gmo-daangn
  profiles:
    default: dev

app:
  notification:
    redis:
      pubsub-channel: ${NOTIFICATION_REDIS_PUBSUB_CHANNEL:notification:sse}