spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

#  mail:
#    host: smtp.naver.com
#    port: ${MAIL_PORT}
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          timeout: 5000
#          ssl:
#            enable: true
#            protocols: TLSv1.2

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 3s
      connect-timeout: 3s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

app:
  payment-link-base-url: "http://localhost:8080"

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type.descriptor.sql: trace
      springframework:
        mail: debug
jwt:
  access_secret: ${ACCESS_JWT_KEY}
#  refresh_secret: ${REFRESH_JWT_KEY}

# 모니터링 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 엔드포인트 노출 (개발용)
      base-path: /actuator

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  health:
    redis:
      enabled: true

  metrics:
    enable:
      jvm: true
      system: true
      tomcat: true
      process: true
      hikaricp: true
      jdbc: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true